version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: controlsystem
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 10.102.0.50

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adm@controlsystem.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5051:80"
    depends_on:
      - db

networks:
  default:
    attachable: true
    ipam:
      config:
        - subnet: 10.102.0.0/16
